### ISSUE TITLE
Docker image pulls fail on Windows due to bad Content-Type/Length

### ISSUE THREAD

**Issue by rssk** [apocas/docker-modem#90] opened 2018-03-30 01:32 UTC
## Problem
This is the same as the issue [here](https://github.com/apocas/dockerode/issues/347), on a `pull` the docker daemon responds to with an error: `context cancelled`. The issues seems to be a couple of things:
* the `Content-Length` is calculated using a `data` payload that is never sent in the request. Perhaps the query string should be used https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L167 ?
* `undefined` `opts` are passed in as `'undefined'` strings, eg: `tag`, leading to empty query params
* the `Content-Type` is set as `application/json` though no json payload is sent, maybe `application/x-www-form-urlencoded` or `text/plain`?

Here is an example failing request `options`, changing the type to `text/plain` _or_ removing the `Content-length` fixes the issue.
```js
 { path: '/images/create?fromImage=coinstac%2Fcoinstac-base&tag=',
   method: 'POST',
   headers: { 'Content-Type': 'application/json', 'Content-Length': 38 },
   key: undefined,
   cert: undefined,
   ca: undefined,
   socketPath: '//./pipe/docker_engine' }
```

**Comment by apocas** [comment] 2018-04-02 21:03
Humm indeed strange.

When I have time I will build a Windows env to debug this one.

**Comment by bompi88** [comment] 2018-08-27 10:18
@apocas did you get time to look into this issue?

**Comment by apocas** [comment] 2018-08-29 11:55
I'm able to run the image pull test on Windows.
https://github.com/apocas/dockerode/blob/master/test/docker.js#L184

Using Windows 10 and latest Docker version.

**Comment by apocas** [comment] 2019-09-23 19:33
Will close this one for now.
Will reopen if more info is provided.

**Closed by apocas** 2019-09-23 19:33 UTC
Labels: needs inspection

**Comment by hvaara** [comment] 2019-09-24 14:44
Thanks for taking the time to look at this, and I fully understand closing this after more than a year of feedback.

We were seeing this and were able to reproduce it consistently. Since then we've implemented a workaround to mitigate the issue. We only saw this on Windows machines. Not on Mac and Linux. The image pull fails multiple times, until it eventually succeeds. How many retries is necessary is not consistent. Some times it's 1, some times it's 20, but usually between 5 to 15 retries is needed.

I'll see if I can find some time to investigate. If I do I'll report my findings here.
